spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm.admin-user:
  id: demo
  password: demo


server:
  port: 8635

camunda:
  bpm:
    deployment-resource-pattern:
      - classpath*:**/*.bpmn
      - classpath*:**/*.bpmn20.xml
      - classpath*:**/*.dmn
      - classpath*:**/*.dmn11.xml
      - classpath*:**/*.form


spring:
  application:
    name: booking-management
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hotel_management
    username: postgres
    password: BigMitch@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


# Discovery Server Access
eureka:
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
    healthcheck:
      enabled: true


logging:
  file:
    name: mts/logs/hotel-management.log
  level:
    root: info
    mts.mtech.useraccountsv2: debug
